### ISSUE TITLE
Invalid URL '/socket/notification' 

### ISSUE THREAD

**Issue by deathInTheAfternoon** [Fixel-Institute/BRAVO#8]
**Description**
I've tried a build on Linux and WSL2, but I've not been able to get beyond registration or login screens. 

If the server is run via daphne or python3 (startServer.sh), when selecting Registration or Login on the Client, I see the following on both Edge and Chrome:
```
Uncaught runtime errors:
ERROR
Failed to construct 'WebSocket': The URL '/socket/notification' is invalid.
    at http://localhost:3000/static/js/bundle.js:19566:18
    at commitHookEffectListMount (http://localhost:3000/static/js/bundle.js:326993:30)
    at commitPassiveMountOnFiber (http://localhost:3000/static/js/bundle.js:328486:17)
    at commitPassiveMountEffects_complete (http://localhost:3000/static/js/bundle.js:328458:13)
    at commitPassiveMountEffects_begin (http://localhost:3000/static/js/bundle.js:328448:11)
    at commitPassiveMountEffects (http://localhost:3000/static/js/bundle.js:328438:7)
    at flushPassiveEffectsImpl (http://localhost:3000/static/js/bundle.js:330323:7)
    at flushPassiveEffects (http://localhost:3000/static/js/bundle.js:330275:18)
    at http://localhost:3000/static/js/bundle.js:330090:13
    at workLoop (http://localhost:3000/static/js/bundle.js:333020:38)
```

**To Reproduce**
Follow Linux build instructions as provided on WSL2 then direct browser to 'http://localhost:3000/index'. Click Register or Login.
I've tried on v2.1.1 and v2.2.0 of BRAVO.

**Comment by deathInTheAfternoon** [comment]
Of course, as soon as I wrote the above I noticed the service url (on the /index page) was set to 'localhost'. Choosing the endpoint 'localhost:3001' got past the above.
